kind: pipeline
name: docker-deploy-develop

steps:
  - name: test
    image: cypress/included:6.2.1
    command:
      - npm ci
      - npm run test

  - name: publish-tezedge-explorer-image
    image: plugins/docker
    depends_on:
      - test
    settings:
      repo: simplestakingcom/tezedge-explorer
      tag: latest
      dockerfile: Dockerfile
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_pswd

trigger:
  branch: develop
  event: push
