kind: pipeline
name: docker-deploy-develop

steps:
  - name: test
    image: node
    commands:
      - npm install
      - npm run start
      - npm run test:run

  - name: build-tezedge-explorer-image
    image: plugins/docker
    depends_on:
      -test
    settings:
      repo: simplestakingcom/tezedge-explorer
      tag: latest
      dockerfile: Dockerfile
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_pswd

trigger:
  branch: develop
  event: push
