kind: pipeline
name: docker-deploy-develop

steps:
  - name: build
    image: node
    volumes:
      - name: cache
        path: /drone/src/node_modules
    commands:
      - npm install

  - name: test
      image: cypress/included:6.2.1
      depends_on:
        - build
      commands:
        - npm test

  - name: publish-tezedge-explorer-image
    image: plugins/docker
    depends_on:
      - test
    settings:
      repo: simplestakingcom/tezedge-explorer
      tag: latest
      dockerfile: Dockerfile
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_pswd

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache/node_modules

trigger:
  branch: develop
  event: push
