kind: pipeline
name: docker-deploy-develop

steps:
  - name: test
    image: node
    commands:
      - npm install --quiet
      - apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - npm run test

  - name: build-tezedge-explorer-image
    image: plugins/docker
    depends_on:
      - test
    settings:
      repo: simplestakingcom/tezedge-explorer
      tag: latest
      dockerfile: Dockerfile
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_pswd

trigger:
  branch: develop
  event: push
