version: '3'
services:
  tezedge-explorer:
    image: simplestakingcom/tezedge-explorer:latest
    build:
      context: docker
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
#      - SANDBOX=${SANDBOX}
#      - API=${API}
      - SANDBOX=https://carthage.tezedge.com:3030
      - API=[{"id":"rust","name":"rust.master.dev.tezedge","http":"http://master.dev.tezedge.com:18732","debugger":"http://master.dev.tezedge.com:17732","ws":"ws://master.dev.tezedge.com:4927"}]
    hostname: tezedge-explorer
    # network_mode: host
