version: '3'
services: 
  tezedge-node-explorer:
    image: node:12.2.0 
    ports: 
      - "4200:4200"
    volumes:
      - ..:/app
    working_dir: /app
    command: bash -c "npm i && ./node_modules/.bin/ng serve --host 0.0.0.0"

